-- Add up migration script here
create table remedy
(
    id         int            not null,
    condition  text           not null,
    statement  text           not null,
    n          int                null,
    unit       text               null,
    oath_id    int            not null,
    created_at timestamptz(6) not null default now()
);
alter table remedy alter column id add generated by default as identity;
alter table remedy add constraint pk_remedy_id primary key(id);
alter table remedy add constraint fk_remedy_oath foreign key (oath_id) references oath (id);