-- Add up migration script here
create table oath
(
	id int not null,
	target text not null,
	penalty text not null,
	conditional_remedies jsonb null,
	"until" timestamptz(3) not null
);

alter table oath alter column id add generated by default as identity;
alter table oath add constraint pk_oath_id primary key(id);